# Generated by Django 3.2.4 on 2021-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210608_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
