# Generated by Django 3.2.4 on 2021-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
