# Generated by Django 3.2.4 on 2021-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210609_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='avg_score',
            field=models.FloatField(default=0),
        ),
    ]
