# Generated by Django 3.2.4 on 2021-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_score_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date_created',
            field=models.DateTimeField(default=None),
        ),
    ]
