# Generated by Django 3.2.4 on 2021-06-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_score_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date_created',
        ),
    ]
