# Generated by Django 3.2.4 on 2021-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_remove_score_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
