# Generated by Django 3.2.4 on 2021-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0004_alter_score_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('avg_score', models.FloatField()),
                ('subject', models.ManyToManyField(to='subject.Subject')),
            ],
        ),
    ]
