# Generated by Django 3.2.4 on 2021-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0002_auto_20210609_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='avg_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
