# Generated by Django 3.2.4 on 2021-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0003_alter_pupil_avg_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='name',
            field=models.CharField(default='Алия', max_length=30),
        ),
    ]
