# Generated by Django 3.2.4 on 2021-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0004_alter_pupil_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
    ]
